services:
  - type: web
    name: iconta24-strapi
    env: node
    region: frankfurt
    plan: free
    buildCommand: bun install && bun run build
    startCommand: bun run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 1337
      - key: DATABASE_CLIENT
        value: postgres
      - key: DATABASE_URL
        fromDatabase:
          name: iconta24-db
          property: connectionString
    healthCheckPath: /admin

databases:
  - name: iconta24-db
    databaseName: iconta24
    user: iconta24_user
    region: frankfurt
    plan: free